function testClassificationTask()
% Функция осуществляет тестирование МСП на базе данных  из каталога
% preparedDataSets на решении задач классификации. Результаты работы 
% выводятся в соответствующий файл каталога testClassificationTask

clc;
clear all;

global flogid;
flogid = 1;

% список имен файлов, содержащих исходные данные для наборов множеств ИНС
filenames = {...   
        'cancer1',...
        'cancer2',...
        'cancer3',...
        'card1',...
        'card2',...
        'card3',...
        'diabetes1',...
        'diabetes2',...
        'diabetes3',...
        'gene1',...
        'gene2',...
        'gene3',...
        'glass1',...
        'glass2',...
        'glass3',...
        'horse1',...  
        'horse2',...  
        'horse3',...  
        'mushroom1',...
        'mushroom2',...
        'mushroom3',...        
        'soybean1',...
        'soybean2',...
        'soybean3',...        
        'thyroid1',...
        'thyroid2',...
        'thyroid3', ...
        'textureCR', ...
        'vowels', ...
        'nXOR'
    };

tic;
fprintf('\nНачало обработки базы тестовых задач...');

for k = 1:length(filenames)  
    
    path = strcat('./learnedTasks/', filenames(k), '_text__log.dat');
    flogid = fopen(char(path), 'w');
    if(flogid == -1)
        error('Test: Не могу открыть файл %s', filenames(k));
    end
    
    fprintf('\n\tОбрабатывается %s', char(filenames(k)));        
    
    % загрузка соответствующего набора данных
    ds = loadDataSets(char(filenames(k)));
    
    % создание МСП заданной архитектуры
    net = mlpCreate([ds.numInputs, 10, 8, ds.numOutputs], ...
                    {'tansig'; 'tansig'; 'tansig'});

    % обучение сети
    [net, errors] = mlpTrain(net, ds);  
    
    % сохранение обученной сети в файл
    path = strcat('./learnedTasks/', filenames(k), '_mlp');
    mlpSave(net, char(path));
    
    % сохранение графика обучения в файл
    path = strcat('./learnedTasks/', filenames(k), '_log');
    mlpPlot(char(path), errors, false);
    
    % сохранение лога обучения в файл
    path = strcat('./learnedTasks/', filenames(k), '_errors');
    save(char(path), 'errors');
    
    % тестирование сети
    printMessage('\n\tТестирование МСП на обучающем множестве');
    printMLPEvalLog(net, ds.training);
    if(ds.hasTest)
        printMessage('\n\tТестирование МСП на тестовом множестве');
        printMLPEvalLog(net, ds.test);
    end
    if(ds.hasValidation)
        printMessage('\n\tТестирование МСП на контрольном множестве');
        printMLPEvalLog(net, ds.validation);
    end

    % сохранение лога обучения в файл
    path = strcat('./learnedTasks/', filenames(k), '_errors_matlab_mlp');

    % создание и обучение МСП Matlab
    mlpMatlabTest(ds, path, ds.numInputs, 10, 8);
    
    fclose(flogid);
    pause(1);
end

fprintf('\nОбработка базы завершена. %d задач за %8.3f с\n', ...
            length(filenames), toc);
end % of function    